# coding: utf-8

# flake8: noqa

"""
    Explore API

    The Opendatasoft Explore API v2 is organized around REST. It provides access to all the data available through the platform in a coherent, hierarchical way.  - Only the HTTP `GET` method is supported. - All API endpoints return JSON. - Endpoints are organized in a hierarchical way describing the relative relationship between objects. - All responses contain a list of links allowing easy and relevant navigation through the API endpoints. - All endpoints use the [Opendatasoft Query Language (ODSQL)](https://help.opendatasoft.com/apis/ods-explore-v2/#section/Opendatasoft-Query-Language-(ODSQL)). This means that, most of the time, parameters work the same way for all endpoints. - While the `records` endpoint is subject to a [limited number of returned records](https://help.opendatasoft.com/apis/ods-explore-v2/#tag/Dataset/operation/getRecords), the `exports` endpoint has no limitations.

    The version of the OpenAPI document: v2.1
    Contact: support@opendatasoft.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "21.0.1"

# import apis into sdk package
from opendatasoft_explore_async.api.catalog_api import CatalogApi
from opendatasoft_explore_async.api.dataset_api import DatasetApi

# import ApiClient
from opendatasoft_explore_async.api_response import ApiResponse
from opendatasoft_explore_async.api_client import ApiClient
from opendatasoft_explore_async.configuration import Configuration
from opendatasoft_explore_async.exceptions import OpenApiException
from opendatasoft_explore_async.exceptions import ApiTypeError
from opendatasoft_explore_async.exceptions import ApiValueError
from opendatasoft_explore_async.exceptions import ApiKeyError
from opendatasoft_explore_async.exceptions import ApiAttributeError
from opendatasoft_explore_async.exceptions import ApiException

# import models into sdk package
from opendatasoft_explore_async.models.attachment import Attachment
from opendatasoft_explore_async.models.attachment_metas import AttachmentMetas
from opendatasoft_explore_async.models.dataset import Dataset
from opendatasoft_explore_async.models.dataset_attachments_inner import DatasetAttachmentsInner
from opendatasoft_explore_async.models.dataset_fields_inner import DatasetFieldsInner
from opendatasoft_explore_async.models.datasets import Datasets
from opendatasoft_explore_async.models.enum_format_datasets import EnumFormatDatasets
from opendatasoft_explore_async.models.facet_enumeration import FacetEnumeration
from opendatasoft_explore_async.models.facet_value_enumeration import FacetValueEnumeration
from opendatasoft_explore_async.models.get_dataset_attachments200_response import GetDatasetAttachments200Response
from opendatasoft_explore_async.models.get_datasets400_response import GetDatasets400Response
from opendatasoft_explore_async.models.get_datasets429_response import GetDatasets429Response
from opendatasoft_explore_async.models.get_datasets_facets200_response import GetDatasetsFacets200Response
from opendatasoft_explore_async.models.links import Links
from opendatasoft_explore_async.models.list_export_formats200_response import ListExportFormats200Response
from opendatasoft_explore_async.models.record import Record
from opendatasoft_explore_async.models.records import Records
